net/mlx5: fix compilation on top of MLNX OFED 4.5
commit[1] was backported wrongly, causing compilation issue
on top of MLNX_OFED4.5:

dpdk.org/drivers/net/mlx5/mlx5_flow.c:43:8:
error: redefinition of 'struct ibv_flow_spec_counter_action'

It is caused because the PMD wrongly assumes the flow counter
struct does not exists on the verbs header file.

Fixing it by removing the dummy definition and protecting the structs
in a different way.

[1]
Fixes: c74ede60bda7 ("net/mlx5: fix build with rdma-core v19")

Change-Id: Ieefa9f3ad896198e285e81b775ded1f4356292f9
Partial-bug: #1781402
Signed-off-by: Shahaf Shuler <shahafs@mellanox.com>